Sure, here's the contents for the file: /garden-bot/garden-bot/fly.toml

app = "garden-bot"

[build]
  dockerfile = "Dockerfile"

[env]
  TELEGRAM_TOKEN = "your_telegram_bot_token"
  API_URL = "https://stock-tracker-iota-steel.vercel.app/api/garden"

[deploy]
  release_command = "python src/bot.py"